language: java
jdk: oraclejdk7
install: true
before_script:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sleep 3
script:
  - mvn clean install
after_failure:
  - cat /home/travis/build/borisbrodski/Jnario/tests/org.jnario.tests/target/work/data/.metadata/.log
